export const sampleBooks = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbnNo: "9780743273565",
    genre: "FICTION",
    quantity: 10,
    description: "A story of ambition and love in the 1920s.",
  },
  {
    title: "1984",
    author: "George Orwell",
    isbnNo: "9780451524935",
    genre: "FICTION",
    quantity: 15,
    description: "A chilling vision of a totalitarian future.",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbnNo: "9780547928227",
    genre: "FANTASY",
    quantity: 8,
    description: "The classic tale of Bilbo Baggins.",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbnNo: "9780061120084",
    genre: "FICTION",
    quantity: 12,
    description: "A masterpiece of modern literature.",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbnNo: "9780316769488",
    genre: "FICTION",
    quantity: 5,
    description: "A story about innocence and disillusionment.",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbnNo: "9780060850524",
    genre: "SCIENCE_FICTION",
    quantity: 7,
    description: "A dark vision of a dystopian society.",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbnNo: "9780062315007",
    genre: "FICTION",
    quantity: 20,
    description: "A journey of transformation and self-discovery.",
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    isbnNo: "9780132350884",
    genre: "CSE",
    quantity: 10,
    description: "A handbook of agile software craftsmanship.",
  },
  {
    title: "Refactoring",
    author: "Martin Fowler",
    isbnNo: "9780134757599",
    genre: "CSE",
    quantity: 6,
    description: "Improving the design of existing code.",
  },
  {
    title: "Design Patterns",
    author: "Erich Gamma",
    isbnNo: "9780201633610",
    genre: "CSE",
    quantity: 4,
    description: "Elements of reusable object-oriented software.",
  },
  {
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    isbnNo: "9780135957059",
    genre: "CSE",
    quantity: 9,
    description: "Your journey to mastery.",
  },
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    isbnNo: "9780262033848",
    genre: "CSE",
    quantity: 3,
    description: "The definitive guide to algorithms.",
  },
  {
    title: "The Art of Computer Programming",
    author: "Donald Knuth",
    isbnNo: "9780201896831",
    genre: "CSE",
    quantity: 5,
    description: "Fundamental algorithms.",
  },
  {
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson",
    isbnNo: "9780262510875",
    genre: "CSE",
    quantity: 4,
    description: "The wizard book of computer science.",
  },
  {
    title: "Effective Java",
    author: "Joshua Bloch",
    isbnNo: "9780134685991",
    genre: "CSE",
    quantity: 12,
    description: "A guide to the Java platform.",
  },
  {
    title: "Head First Design Patterns",
    author: "Eric Freeman",
    isbnNo: "9780596007126",
    genre: "CSE",
    quantity: 8,
    description: "A brain-friendly guide to design patterns.",
  },
  {
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    isbnNo: "9780984782857",
    genre: "CSE",
    quantity: 15,
    description: "189 programming questions and solutions.",
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    isbnNo: "9780198788607",
    genre: "SCIENCE_FICTION",
    quantity: 6,
    description: "A landmark in evolutionary biology.",
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbnNo: "9780062316097",
    genre: "HISTORY",
    quantity: 10,
    description: "The history of the human species.",
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    isbnNo: "9781585424337",
    genre: "SELF_HELP",
    quantity: 20,
    description: "The classic guide to success and wealth.",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbnNo: "9780735211292",
    genre: "SELF_HELP",
    quantity: 25,
    description: "An easy way to build good habits.",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    isbnNo: "9780812981605",
    genre: "SELF_HELP",
    quantity: 11,
    description: "Why we do what we do in life and business.",
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    isbnNo: "9781455586691",
    genre: "SELF_HELP",
    quantity: 14,
    description: "Rules for focused success in a distracted world.",
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbnNo: "9780307887894",
    genre: "SELF_HELP",
    quantity: 9,
    description: "How today's entrepreneurs use continuous innovation.",
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    isbnNo: "9780804139298",
    genre: "SELF_HELP",
    quantity: 13,
    description: "Notes on startups, or how to build the future.",
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    isbnNo: "9780441172719",
    genre: "SCIENCE_FICTION",
    quantity: 18,
    description: "The epic tale of Paul Atreides.",
  },
  {
    title: "Foundation",
    author: "Isaac Asimov",
    isbnNo: "9780553293357",
    genre: "SCIENCE_FICTION",
    quantity: 12,
    description: "The crumbling of a galactic empire.",
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    isbnNo: "9780441569595",
    genre: "SCIENCE_FICTION",
    quantity: 7,
    description: "The definitive cyberpunk novel.",
  },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    isbnNo: "9780553380958",
    genre: "SCIENCE_FICTION",
    quantity: 6,
    description: "A high-speed journey through the metaverse.",
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    isbnNo: "9780553418026",
    genre: "SCIENCE_FICTION",
    quantity: 10,
    description: "A biologist survives alone on Mars.",
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbnNo: "9781451648539",
    genre: "BIOGRAPHY",
    quantity: 8,
    description: "The exclusive biography of the Apple founder.",
  },
  {
    title: "Elon Musk",
    author: "Ashlee Vance",
    isbnNo: "9780062301239",
    genre: "BIOGRAPHY",
    quantity: 9,
    description: "Tesla, SpaceX, and the quest for a fantastic future.",
  },
  {
    title: "Shoe Dog",
    author: "Phil Knight",
    isbnNo: "9781501135910",
    genre: "BIOGRAPHY",
    quantity: 12,
    description: "A memoir by the creator of Nike.",
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    isbnNo: "9780307474278",
    genre: "MYSTERY",
    quantity: 14,
    description: "A secret society hides a religious mystery.",
  },
  {
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    isbnNo: "9780553212419",
    genre: "MYSTERY",
    quantity: 20,
    description: "The complete adventures of the great detective.",
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    isbnNo: "9780307949486",
    genre: "MYSTERY",
    quantity: 11,
    description: "A dark and gripping thriller.",
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbnNo: "9780307588371",
    genre: "MYSTERY",
    quantity: 9,
    description: "A marriage turns into a psychological nightmare.",
  },
  {
    title: "Big Little Lies",
    author: "Liane Moriarty",
    isbnNo: "9780425274866",
    genre: "MYSTERY",
    quantity: 7,
    description: "Secrets, lies, and a murder in a quiet town.",
  },
  {
    title: "The Shining",
    author: "Stephen King",
    isbnNo: "9780307743657",
    genre: "HORROR",
    quantity: 10,
    description: "A family stays in an isolated hotel.",
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    isbnNo: "9780141439846",
    genre: "HORROR",
    quantity: 8,
    description: "The legendary vampire tale.",
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    isbnNo: "9780141439471",
    genre: "HORROR",
    quantity: 6,
    description: "A scientist creates a living creature.",
  },
  {
    title: "The Silence of the Lambs",
    author: "Thomas Harris",
    isbnNo: "9780312924584",
    genre: "HORROR",
    quantity: 5,
    description: "An FBI trainee gets help from a serial killer.",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbnNo: "9780141439518",
    genre: "ROMANCE",
    quantity: 12,
    description: "A classic story of manners and love.",
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    isbnNo: "9780525478812",
    genre: "ROMANCE",
    quantity: 15,
    description: "Two teens fall in love in a cancer support group.",
  },
  {
    title: "The Notebook",
    author: "Nicholas Sparks",
    isbnNo: "9781455582877",
    genre: "ROMANCE",
    quantity: 10,
    description: "A lasting love that survives all tests.",
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbnNo: "9780553380163",
    genre: "SCIENCE_FICTION",
    quantity: 14,
    description: "The fundamental laws of the universe.",
  },
  {
    title: "The Cosmos",
    author: "Carl Sagan",
    isbnNo: "9780345331359",
    genre: "SCIENCE_FICTION",
    quantity: 9,
    description: "A journey through space and time.",
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    isbnNo: "9780393317558",
    genre: "HISTORY",
    quantity: 8,
    description: "The fates of human societies.",
  },
  {
    title: "The Silk Roads",
    author: "Peter Frankopan",
    isbnNo: "9781101912379",
    genre: "HISTORY",
    quantity: 7,
    description: "A new history of the world.",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbnNo: "9780812968255",
    genre: "SELF_HELP",
    quantity: 20,
    description: "The private reflections of a Roman Emperor.",
  },
];
